### ISSUE TITLE
429 응답때문에 업데이트가 되지 않는 현상

### ISSUE THREAD

**Issue by ingyu1008** [inscrutable-plus/inscrutable_backend#6]
한번에 너무 많은 api call을 시도하면 발생하는 것으로 확인함.

따라서 다음을 통해 /update API를 수정해야함

1. 티어별 문제 업데이트 : 한 번에 200번의 콜 대신 30번으로 나누기 때문에 항상 가능함
2. 핸들별 솔브 업데이트 : 한 번에 모든 핸들을 업데이트하는 것은 무리임

**Comment by thak1411** [comment]
한 쿼리당 10초 혹은 30초 등 많은 딜레이를 주어 업데이트가 매우 느리지만, 확정적으로 업데이트 하는게 좋을 듯
하루에 한 번 자동화해서 작업할 것이므로 시간은 문제될 것 같지 않음
